name: Build and Package

on:
  push:
    branches:
      - main  # 你可以根据需要更改分支名称

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Download UPX
      run: |
        Invoke-WebRequest -Uri https://github.com/upx/upx/releases/download/v4.1.0/upx-4.1.0-win64.zip -OutFile upx.zip
        Expand-Archive -Path upx.zip -DestinationPath upx
        Set-Location -Path upx
        Copy-Item -Path .\upx.exe -Destination $env:GITHUB_WORKSPACE\upx.exe
      shell: powershell

    - name: Install dependencies
      run: pip install pyinstaller
      working-directory: ${{ github.workspace }}

    - name: Build EXE
      run: |
        pyinstaller --onefile -w -F -upx test1.py
      working-directory: ${{ github.workspace }}

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: test1
        path: test1.exe
