name: Build and Package Python App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pywin32
      shell: bash

    - name: Build exe
      run: |
        pyinstaller -F --onefile -w --upx-dir=/path/to/upx test1.py
      shell: bash

    - name: Compress exe with UPX
      run: |
        /path/to/upx/upx -o /path/to/output/folder/test1.exe /path/to/build/folder/test1
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-exe
        path: /path/to/output/folder/test1.exe
